### ISSUE TITLE
프로젝트 구성에 대한 질문

### ISSUE THREAD

**Issue by rumbarum** [teamhide/fastapi-boilerplate#13]
안녕하세요, 올려주신 작업에 감사합니다. 
올려주신 것 기반으로 프로젝트 구성해보려고 하고 있는데 궁금한  것이 있어 질문 드립니다. 

1. Api Layer를 app/resource 하위에 다 넣고 (django 처럼) resouce 별 schema를 같이 모으면 더 불편할까요?

2. BaseRepo 가 있는데 별도로 활용은 되고 있지 않아서 api -> service -> repository 로  의도하신거라고 보면 될까요?

**Comment by teamhide** [comment]
안녕하세요. 답변이 늦었습니다.

1. 프로젝트 구성은 각자 편한대로 구성해서 사용하시면 됩니다. 딱히 불편할 것 같진 않네요 :)
2. Layered architecture를 채택해서 사용하시는 분들을 위해 만들어놨습니다. 다만, 사용하지 않으셔도 좋습니다.
