### ISSUE TITLE
Benchmarking strategy is wrong here....

### ISSUE THREAD

**Issue by ManiMozaffar** [teamhide/fastapi-boilerplate#23]
Hey,

I just noticed that you didn't use same driver when benchmarking these ORMs,
so it gave tortoise a not deserved boost!
I believe you should have used all with psycopg2, since all support it as far as I know.
Or maybe perform a sync and async benchmark driver, then compare them. Those who supports async driver usually supports asyncpg, since it's best out there.

**Comment by teamhide** [comment]
I replaced PostgreSQL to MySQL. Please check latest codes.
