### ISSUE TITLE
Can't open files in static folder

### ISSUE THREAD

**Issue by r0otx** [teamhide/fastapi-boilerplate#25]
I'm was mount static folder and can't get images in browser. I'm was see error 
`Unicodedecodeerror: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte`
How fix it? I comment block code
`            elif message.get("type") == "http.response.body":
                if body := message.get("body"):
                    response_info.body += body.decode("utf8")`

in response_log and it work for me.

**Comment by teamhide** [comment]
The code that logs the response was missing exception handling for the file. I will add it soon.
