### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by abhishakegupta91** [teamhide/fastapi-boilerplate#26]
Received `AttributeError: 'str' object has no attribute 'decode'`

At line: https://github.com/teamhide/fastapi-boilerplate/blob/master/core/utils/token_helper.py#L19

**Comment by HeroSony** [comment]
@abhishakegupta91, have you fixed it? I've got the same error.

**Comment by HeroSony** [comment]
I've fixed by just simply drop the .decode('utf-8').

**Comment by teamhide** [comment]
Sorry for the late reply. The revision has been reflected in the latest code. Please pull it.

**Comment by abhishakegupta91** [comment]
Thanks
