### ISSUE TITLE
[Question]: What is difference between local and dev environments

### ISSUE THREAD

**Issue by darkido** [teamhide/fastapi-boilerplate#9]
I know development and production environments purposes and  I've seen using name of `local` instead of `dev` for local development.
but haven't seen using both of them.
Could you guide me what is their difference?

**Comment by teamhide** [comment]
`dev` is a configuration value for the docker environment, and `local` is a configuration value for the local environment. However, please note that it may vary depending on the settings you are using.

**Comment by teamhide** [comment]
I don't want you to get too tied up in the code structure in this project. The purpose of this project is to modify and use it according to the user's own needs :)

**Comment by darkido** [comment]
> `dev` is a configuration value for the docker environment, and `local` is a configuration value for the local environment. 

Thanks for clarifying this, It makes sense now. 

> I don't want you to get too tied up in the code structure in this project.

Right but I can't help myself, it's really amazing 💯 and I'm sorry I want to dig into your code more 😔

**Comment by teamhide** [comment]
It may be difficult for those who are new to fastapi. I'll add a part about the guide when I have time.
